name: superlists
dependencies:
- django=1.8.2=py34_0
- gunicorn=19.1.0=py34_0
- openssl=1.0.1k=1
- pastedeploy=1.5.2=py34_1
- pip=7.0.3=py34_0
- python=3.4.3=1
- readline=6.2=2
- requests=2.7.0=py34_0
- setuptools=17.1.1=py34_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- xz=5.0.5=0
- zlib=1.2.8=0
